# Generated by Django 4.0.1 on 2022-10-17 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='mobile',
            field=models.PositiveIntegerField(),
        ),
    ]
