# Generated by Django 4.0.1 on 2022-10-18 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcart', '0003_remove_cartitems_product_cartitems_product'),
        ('item_order', '0003_order_product_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodcart.cartitems')),
            ],
        ),
    ]
