# Generated by Django 4.0.1 on 2022-10-18 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_order', '0004_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product_name',
            field=models.TextField(max_length=100),
        ),
    ]
