# Generated by Django 4.0.1 on 2022-10-23 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_order', '0005_remove_order_product_order_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
