# Generated by Django 4.0.1 on 2022-10-18 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item_order', '0006_remove_order_product_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
