# Generated by Django 4.0.1 on 2022-10-18 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item_order', '0008_order_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product_name',
        ),
    ]
