# Generated by Django 4.0.1 on 2022-10-23 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcart', '0001_initial'),
        ('item_order', '0008_remove_order_product_order_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cartitem',
        ),
        migrations.AddField(
            model_name='order',
            name='cartitem',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='foodcart.cartitems'),
            preserve_default=False,
        ),
    ]
