# Generated by Django 4.0.1 on 2022-10-23 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcart', '0001_initial'),
        ('item_order', '0009_remove_order_cartitem_order_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cartitem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='foodcart.cartitems'),
        ),
    ]
