# Generated by Django 4.0.1 on 2022-10-23 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_order', '0010_alter_order_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cartitem',
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
