# Generated by Django 4.0.1 on 2022-10-18 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item_order', '0011_remove_order_cart_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product_name',
        ),
    ]
