# Generated by Django 4.0.1 on 2022-10-23 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item_order', '0012_orderitem_cart_orderitem_price_orderitem_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='price',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='quantity',
        ),
    ]
