# Generated by Django 4.0.1 on 2022-10-18 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcart', '0003_remove_cartitems_product_cartitems_product'),
        ('item_order', '0012_remove_order_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cart_item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='foodcart.cartitems'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='product_name',
            field=models.JSONField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
