# Generated by Django 4.0.1 on 2022-10-17 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_remove_cartitem_cart_remove_cartitem_food_and_more'),
        ('foodcart', '0002_remove_cartitems_product_cartitems_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitems',
            name='product',
        ),
        migrations.AddField(
            model_name='cartitems',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='menu.menuitem'),
            preserve_default=False,
        ),
    ]
