# Generated by Django 4.0.1 on 2022-08-17 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_cart_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='total_items',
        ),
    ]
