# Generated by Django 4.0.1 on 2022-08-17 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_remove_cartitem_total_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
