# Generated by Django 4.0.1 on 2022-08-22 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_menuitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='total_items',
            field=models.IntegerField(default=0),
        ),
    ]
