# Generated by Django 4.0.1 on 2022-08-22 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_cartitem_total_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='total_items',
        ),
    ]
