# Generated by Django 4.0.1 on 2022-08-22 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_remove_cartitem_total_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='food',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='user',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
